In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [4]:
#  Encode categorical variables

label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
# Combine one-hot encoded columns with original data

data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
# Split the data into features and target
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

## Split the data in training and tetsing sets

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Regression Problem Statement

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

WARNING:tensorflow:From e:\Machine learning Main\gen ai\kris naik udemy\ann\annclassification\ANN\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [15]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

WARNING:tensorflow:From e:\Machine learning Main\gen ai\kris naik udemy\ann\annclassification\ANN\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From e:\Machine learning Main\gen ai\kris naik udemy\ann\annclassification\ANN\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [18]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [19]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From e:\Machine learning Main\gen ai\kris naik udemy\ann\annclassification\ANN\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From e:\Machine learning Main\gen ai\kris naik udemy\ann\annclassification\ANN\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 8ms/step - loss: 100390.3047 - mae: 100390.3047 - val_loss: 98558.0234 - val_mae: 98558.0234
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 99742.7812 - mae: 99742.7812 - val_loss: 97211.1172 - val_mae: 97211.1172
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 97370.8672 - mae: 97370.8672 - val_loss: 93699.7344 - val_mae: 93699.7344
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 92635.2188 - mae: 92635.2188 - val_loss: 87733.1172 - val_mae: 87733.1172
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 85600.9062 - mae: 85600.9062 - val_loss: 79932.0234 - val_mae: 79932.0234
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 77081.2734 - mae: 77081.2734 - val_loss: 71364.5234 - val_mae: 71364.5234
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 68422.6719 - mae: 68422.6719 - val_loss: 63504.7969 - val_mae: 63504.7969
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 60998.4336 - mae: 60998.4336 - val_loss: 57383.6133 - val_mae: 57383.6133
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 55685.2109 - mae: 55685.2109 - val_loss: 53485.1445 - val_mae: 53485.1445
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 52593.4961 - mae: 52593.4961 - val_loss: 51658.1875 - val_mae: 51658.1875
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 51140.8711 - mae: 51140.8711 - val_loss: 50924.0078 - val_mae: 50924.0078
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50558.9609 - mae: 50558.9609 - val_loss: 50705.7188 - val_mae: 50705.7188
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50328.8828 - mae: 50328.8828 - val_loss: 50633.0273 - val_mae: 50633.0273
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50225.3594 - mae: 50225.3594 - val_loss: 50591.7305 - val_mae: 50591.7305
Epoch 15/100
250/250 [==============================] - 1s 6ms/step - loss: 50171.0078 - mae: 50171.0078 - val_loss: 50566.9805 - val_mae: 50566.9805
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50121.8086 - mae: 50121.8086 - val_loss: 50535.8320 - val_mae: 50535.8320
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50084.8633 - mae: 50084.8633 - val_loss: 50505.5156 - val_mae: 50505.5156
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50051.6797 - mae: 50051.6797 - val_loss: 50479.5156 - val_mae: 50479.5156
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50019.0352 - mae: 50019.0352 - val_loss: 50461.3242 - val_mae: 50461.3242
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 49990.3047 - mae: 49990.3047 - val_loss: 50438.5547 - val_mae: 50438.5547
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49961.0312 - mae: 49961.0312 - val_loss: 50423.1055 - val_mae: 50423.1055
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49937.1719 - mae: 49937.1719 - val_loss: 50404.1445 - val_mae: 50404.1445
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49911.2539 - mae: 49911.2539 - val_loss: 50396.0781 - val_mae: 50396.0781
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49888.6953 - mae: 49888.6953 - val_loss: 50378.8750 - val_mae: 50378.8750
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49865.9805 - mae: 49865.9805 - val_loss: 50364.9961 - val_mae: 50364.9961
Epoch 26/100
250/250 [==============================] - 1s 4ms/step - loss: 49843.1992 - mae: 49843.1992 - val_loss: 50358.6055 - val_mae: 50358.6055
Epoch 27/100
250/250 [==============================] - 1s 5ms/step - loss: 49825.0977 - mae: 49825.0977 - val_loss: 50339.5625 - val_mae: 50339.5625
Epoch 28/100
250/250 [==============================] - 1s 5ms/step - loss: 49802.6602 - mae: 49802.6602 - val_loss: 50342.2188 - val_mae: 50342.2188
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49789.9062 - mae: 49789.9062 - val_loss: 50326.6602 - val_mae: 50326.6602
Epoch 30/100
250/250 [==============================] - 1s 6ms/step - loss: 49772.8945 - mae: 49772.8945 - val_loss: 50307.4805 - val_mae: 50307.4805
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49756.6172 - mae: 49756.6172 - val_loss: 50301.9258 - val_mae: 50301.9258
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 49744.7383 - mae: 49744.7383 - val_loss: 50294.2031 - val_mae: 50294.2031
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49729.1289 - mae: 49729.1289 - val_loss: 50293.4102 - val_mae: 50293.4102
Epoch 34/100
250/250 [==============================] - 1s 5ms/step - loss: 49715.0547 - mae: 49715.0547 - val_loss: 50279.2617 - val_mae: 50279.2617
Epoch 35/100
250/250 [==============================] - 1s 4ms/step - loss: 49703.2852 - mae: 49703.2852 - val_loss: 50281.3477 - val_mae: 50281.3477
Epoch 36/100
250/250 [==============================] - 1s 5ms/step - loss: 49689.8984 - mae: 49689.8984 - val_loss: 50277.7305 - val_mae: 50277.7305
Epoch 37/100
250/250 [==============================] - 1s 5ms/step - loss: 49678.8750 - mae: 49678.8750 - val_loss: 50273.0664 - val_mae: 50273.0664
Epoch 38/100
250/250 [==============================] - 1s 5ms/step - loss: 49670.5078 - mae: 49670.5078 - val_loss: 50270.2656 - val_mae: 50270.2656
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49658.8359 - mae: 49658.8359 - val_loss: 50264.8438 - val_mae: 50264.8438
Epoch 40/100
250/250 [==============================] - 1s 5ms/step - loss: 49647.8672 - mae: 49647.8672 - val_loss: 50265.8477 - val_mae: 50265.8477
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 49638.8320 - mae: 49638.8320 - val_loss: 50255.4883 - val_mae: 50255.4883
Epoch 42/100
250/250 [==============================] - 1s 5ms/step - loss: 49627.7539 - mae: 49627.7539 - val_loss: 50258.3984 - val_mae: 50258.3984
Epoch 43/100
250/250 [==============================] - 1s 5ms/step - loss: 49616.5625 - mae: 49616.5625 - val_loss: 50257.9102 - val_mae: 50257.9102
Epoch 44/100
250/250 [==============================] - 1s 5ms/step - loss: 49606.3906 - mae: 49606.3906 - val_loss: 50250.5039 - val_mae: 50250.5039
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49599.6914 - mae: 49599.6914 - val_loss: 50264.4062 - val_mae: 50264.4062
Epoch 46/100
250/250 [==============================] - 1s 4ms/step - loss: 49590.5508 - mae: 49590.5508 - val_loss: 50246.0977 - val_mae: 50246.0977
Epoch 47/100
250/250 [==============================] - 1s 4ms/step - loss: 49579.8906 - mae: 49579.8906 - val_loss: 50260.1133 - val_mae: 50260.1133
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 49573.8555 - mae: 49573.8555 - val_loss: 50259.8008 - val_mae: 50259.8008
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49565.1406 - mae: 49565.1406 - val_loss: 50249.9961 - val_mae: 50249.9961
Epoch 50/100
250/250 [==============================] - 1s 5ms/step - loss: 49556.3438 - mae: 49556.3438 - val_loss: 50259.4961 - val_mae: 50259.4961
Epoch 51/100
250/250 [==============================] - 1s 5ms/step - loss: 49553.1328 - mae: 49553.1328 - val_loss: 50267.6445 - val_mae: 50267.6445
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49542.3125 - mae: 49542.3125 - val_loss: 50260.0781 - val_mae: 50260.0781
Epoch 53/100
250/250 [==============================] - 1s 4ms/step - loss: 49535.5273 - mae: 49535.5273 - val_loss: 50250.1094 - val_mae: 50250.1094
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49529.0156 - mae: 49529.0156 - val_loss: 50253.9414 - val_mae: 50253.9414
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49522.6055 - mae: 49522.6055 - val_loss: 50253.4883 - val_mae: 50253.4883
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49515.7070 - mae: 49515.7070 - val_loss: 50251.6484 - val_mae: 50251.6484

In [20]:
%load_ext tensorboard

In [23]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 23060), started 0:00:15 ago. (Use '!kill 23060' to kill it.)

In [24]:
## Evaluate model on the test data

test_loss,test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE : {test_mae}")

63/63 [==============================] - 0s 1ms/step - loss: 50246.0977 - mae: 50246.0977
Test MAE : 50246.09765625

In [25]:
model.save('regression_model.h5')

e:\Machine learning Main\gen ai\kris naik udemy\ann\annclassification\ANN\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(